//    Copyright (C) 2025-2026 Miguel Ángel Monreal Velasco
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { Button, Checkbox, Flex, Select, Tooltip } from 'antd';
import useStarCoordinatesStore from '../stores/star-coorditantes-store';
import useConfigStore from '../stores/config-store';
import { useState } from 'react';
import { InfoCircleFilled } from '@ant-design/icons';

const informationTooltipMessage =
	'The scIdColumn is an autogenerated value. If your dataset has a column that can be use as an id you can select it. The id column is ment to be used just for identification, its values have to be unique and they will not be represented.';

const onChange = (onCheck, onUncheck, checked, column) => {
	if (checked) {
		onCheck(column);
	} else {
		onUncheck(column);
	}
};

function ColumnsConfiguration() {
	const idColumn = useConfigStore((state) => state.idColumn);
	const setIdColumn = useConfigStore((state) => state.setIdColumn);
	const setVectorsInitialized = useConfigStore(
		(state) => state.setVectorsInitialized
	);

	const validColumns = useStarCoordinatesStore((state) => state.validColumns);
	const selectedColumns = useStarCoordinatesStore(
		(state) => state.selectedColumns
	);
	const addSelectedColumn = useStarCoordinatesStore(
		(state) => state.addSelectedColumn
	);
	const removeSelectedColumn = useStarCoordinatesStore(
		(state) => state.removeSelectedColumn
	);
	const setValidColumns = useStarCoordinatesStore(
		(state) => state.setValidColumns
	);
	const setSelectedColumns = useStarCoordinatesStore(
		(state) => state.setSelectedColumns
	);

	const [showNotSelectedColumns, setShowNotSelectedColumns] = useState(false);

	const notSelectedColumns = validColumns.filter(
		(column) => !selectedColumns.includes(column)
	);

	return (
		<Flex gap="large" vertical>
			<Flex
				gap="small"
				align="center"
				justify="space-between"
				style={{ width: '100%' }}
			>
				<h3>Id column:</h3>
				{validColumns && (
					<Select
						onChange={(value) => {
							if ('scIdColumn' !== idColumn) {
								addSelectedColumn(idColumn);
							}

							setIdColumn(value);
							removeSelectedColumn(value);

							if ('scIdColumn' !== value) {
								const newValidColumns = validColumns.filter(
									(col) => col !== 'scIdColumn'
								);
								setValidColumns(newValidColumns);
							} else {
								if (!validColumns.includes('scIdColumn')) {
									setValidColumns([...validColumns, 'scIdColumn']);
								}
							}

							setVectorsInitialized(false);
						}}
						value={idColumn}
						style={{ flex: 1 }}
					>
						{validColumns.map((header) => (
							<Select.Option key={header} value={header}>
								{header}
							</Select.Option>
						))}
					</Select>
				)}
				<Tooltip title={informationTooltipMessage}>
					<InfoCircleFilled />
				</Tooltip>
			</Flex>
			<Flex gap="small" vertical>
				{selectedColumns
					.sort((columnA, columnB) => {
						return columnA.localeCompare(columnB);
					})
					.map((column) => (
						<Checkbox
							key={column}
							onChange={(e) => {
								onChange(
									addSelectedColumn,
									removeSelectedColumn,
									e.target.checked,
									column
								);
								setVectorsInitialized(false);
							}}
							checked={true}
							disabled={idColumn === column}
						>
							{column}
						</Checkbox>
					))}
				{notSelectedColumns && notSelectedColumns.length > 0 && (
					<Button
						type="link"
						onClick={() => setShowNotSelectedColumns(!showNotSelectedColumns)}
					>
						{showNotSelectedColumns ? '-' : '+'} Not selected columns
					</Button>
				)}

				{showNotSelectedColumns &&
					notSelectedColumns
						.sort((columnA, columnB) => {
							return columnA.localeCompare(columnB);
						})
						.map((column) => (
							<Checkbox
								key={column}
								onChange={(e) => {
									onChange(
										addSelectedColumn,
										removeSelectedColumn,
										e.target.checked,
										column
									);
									setVectorsInitialized(false);
								}}
								disabled={idColumn === column}
							>
								{column}
							</Checkbox>
						))}
			</Flex>
		</Flex>
	);
}

export default ColumnsConfiguration;
